<a href="https://colab.research.google.com/github/Cesaraventura/data_science/blob/main/Intro_to_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
if False:
    array = np.array([1, 4, 5, 8], float)
    array

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6]], float)

In [8]:
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
array [1]

array([4., 5., 6.])

In [10]:
array [:2]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)

In [17]:
array_1 + array_2

array([[ 6.,  8.],
       [10., 12.]])

In [18]:
array_1 * array_2

array([[ 5., 12.],
       [21., 32.]])

In [19]:
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)

In [20]:
np.mean(array_1)

2.0

In [22]:
np.mean(array_2)

7.0

In [23]:
np.dot(array_1, array_2)

array([44.])

In [24]:
import pandas as pd

In [25]:
series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
series

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object

In [28]:
 series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
series['Instructor']

'Dave'

In [29]:
series[['Instructor', 'Curriculum Manager', 'Course Number']]

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object

In [30]:
cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
cuteness > 3

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool

In [32]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}

In [34]:
football = pd.DataFrame(data)
football

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

In [35]:
football.dtypes

year       int64
team      object
wins       int64
losses     int64
dtype: object

In [36]:
football.describe()

year       wins     losses
count     8.000000   8.000000   8.000000
mean   2011.125000   9.375000   6.625000
std       0.834523   3.377975   3.377975
min    2010.000000   4.000000   1.000000
25%    2010.750000   7.500000   5.000000
50%    2011.000000  10.000000   6.000000
75%    2012.000000  11.000000   8.500000
max    2012.000000  15.000000  12.000000

In [37]:
football.head()

year     team  wins  losses
0  2010    Bears    11       5
1  2011    Bears     8       8
2  2012    Bears    10       6
3  2011  Packers    15       1
4  2012  Packers    11       5

In [38]:
football.tail()

year     team  wins  losses
3  2011  Packers    15       1
4  2012  Packers    11       5
5  2010    Lions     6      10
6  2011    Lions    10       6
7  2012    Lions     4      12

In [43]:
from pandas import DataFrame, Series

In [49]:
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States','Netherlands', 'Germany', 'Switzerland', 'Belarus','Austria','France', 'Poland', 'China', 'Korea','Sweden', 'Czech Republic', 'Slovenia', 'Japan','Finland', 'Great Britain', 'Ukraine', 'Slovakia','Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']
gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]

olympic_medal_counts_df = DataFrame(
       {'countries': countries,
        'gold': gold,
        'silver': silver,
        'bronze': bronze})

In [50]:
olympic_medal_counts_df

countries  gold  silver  bronze
0     Russian Fed.    13      11       9
1           Norway    11       5      10
2           Canada    10      10       5
3    United States     9       7      12
4      Netherlands     8       7       9
5          Germany     8       6       5
6      Switzerland     6       3       2
7          Belarus     5       0       1
8          Austria     4       8       5
9           France     4       4       7
10          Poland     4       1       1
11           China     3       4       2
12           Korea     3       3       2
13          Sweden     2       7       6
14  Czech Republic     2       4       2
15        Slovenia     2       2       4
16           Japan     1       4       3
17         Finland     1       3       1
18   Great Britain     1       1       2
19         Ukraine     1       0       1
20        Slovakia     1       0       0
21           Italy     0       2       6
22          Latvia     0       2       2
23       Australia     0       2       1
24         Croatia     0       1       0
25      Kazakhstan     0       0       1

In [51]:
olympic_medal_counts_df.iloc[[0]]

countries  gold  silver  bronze
0  Russian Fed.    13      11       9

In [52]:
olympic_medal_counts_df.iloc[3:5]

countries  gold  silver  bronze
3  United States     9       7      12
4    Netherlands     8       7       9